# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: format
        name: Run auto formatting
        entry: task format
        language: system
        always_run: true
        pass_filenames: false
      - id: lint
        name: Run lint and format checks
        entry: task lint
        language: system
        always_run: true
        pass_filenames: false
      - id: typecheck
        name: Run type checking
        entry: task typecheck
        language: system
        pass_filenames: false
#      - id: test
#        name: Run tests
#        entry: task test
#        language: system
#        pass_filenames: false
